### ISSUE TITLE
vuepress 2.0.0-beta.61 插件均无法使用

### ISSUE THREAD

**Issue by OrageKK** [denaro-org/vuepress-theme-denaro#1]
大部分报错都是CommonJS的，希望有时间更新一下

**Comment by vxhly** [comment]
请详细提供报错信息，以及使用的插件版本号，（最好附上相关例子的链接）建议您将 vuepress 的相关依赖版本号设置为一致，并且按照插件文档正确配置 config.js

**Comment by vxhly** [comment]
目前 @vuepress-denaro/* 下的依赖 vuepress 插件全部更新至 2.0.0-beta.61 版本，已经发布 1.1.1-beta.0 版本

**Comment by vxhly** [comment]
@OrageKK 更新依赖包之后如果确实有问题，提供一下使用 demo 并重新开一个 issues
